# Generated by Django 4.0.6 on 2022-08-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
