# Generated by Django 4.0.6 on 2022-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_description_alter_listing_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='top_bid',
            field=models.BooleanField(default=False),
        ),
    ]
